// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBIpr0kPxqwIdvFKcx6TDoj2P15G_mJ9Q',
    appId: '1:365610873055:web:5b1fb064b48ff22286f96a',
    messagingSenderId: '365610873055',
    projectId: 'codingbahasa',
    authDomain: 'codingbahasa.firebaseapp.com',
    storageBucket: 'codingbahasa.firebasestorage.app',
    measurementId: 'G-REE78T0F6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZI67tEtKNRvt7jnsD60YmqWVD6rHFBMY',
    appId: '1:365610873055:android:62bf6fc0e19e644d86f96a',
    messagingSenderId: '365610873055',
    projectId: 'codingbahasa',
    storageBucket: 'codingbahasa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNOSbzVqswKtfkmt_Cm-Q6fWz-TPglby4',
    appId: '1:365610873055:ios:5548bc3965b14e7186f96a',
    messagingSenderId: '365610873055',
    projectId: 'codingbahasa',
    storageBucket: 'codingbahasa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNOSbzVqswKtfkmt_Cm-Q6fWz-TPglby4',
    appId: '1:365610873055:ios:5548bc3965b14e7186f96a',
    messagingSenderId: '365610873055',
    projectId: 'codingbahasa',
    storageBucket: 'codingbahasa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBIpr0kPxqwIdvFKcx6TDoj2P15G_mJ9Q',
    appId: '1:365610873055:web:f670ebea64729d2186f96a',
    messagingSenderId: '365610873055',
    projectId: 'codingbahasa',
    authDomain: 'codingbahasa.firebaseapp.com',
    storageBucket: 'codingbahasa.firebasestorage.app',
    measurementId: 'G-E5J95DVBV2',
  );
}
