// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0VNFwEj-L0RIksayV4X--XKp3H8pLAF8',
    appId: '1:499920585403:web:c17cbdf7bf2c3f5f45df9e',
    messagingSenderId: '499920585403',
    projectId: 'coding-bahasa',
    authDomain: 'coding-bahasa.firebaseapp.com',
    storageBucket: 'coding-bahasa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt2sE7Hm6v5v8_6eGwbBs7GbCZPPXe78w',
    appId: '1:499920585403:android:f0c5c5f5f4084c4a45df9e',
    messagingSenderId: '499920585403',
    projectId: 'coding-bahasa',
    storageBucket: 'coding-bahasa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhAwOy_LZEqBweW3wQxN8EdeLtd-vHswI',
    appId: '1:499920585403:ios:40bc83f8e856074a45df9e',
    messagingSenderId: '499920585403',
    projectId: 'coding-bahasa',
    storageBucket: 'coding-bahasa.firebasestorage.app',
    iosBundleId: 'com.example.codingbahasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhAwOy_LZEqBweW3wQxN8EdeLtd-vHswI',
    appId: '1:499920585403:ios:40bc83f8e856074a45df9e',
    messagingSenderId: '499920585403',
    projectId: 'coding-bahasa',
    storageBucket: 'coding-bahasa.firebasestorage.app',
    iosBundleId: 'com.example.codingbahasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0VNFwEj-L0RIksayV4X--XKp3H8pLAF8',
    appId: '1:499920585403:web:1524e32a293fcf8245df9e',
    messagingSenderId: '499920585403',
    projectId: 'coding-bahasa',
    authDomain: 'coding-bahasa.firebaseapp.com',
    storageBucket: 'coding-bahasa.firebasestorage.app',
  );
}
