// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2twFMSRnLwzgkpVun6XZ5YbZCs-UqPao',
    appId: '1:551649646330:web:681170e8bd261025435b43',
    messagingSenderId: '551649646330',
    projectId: 'codingbahasa-app',
    authDomain: 'codingbahasa-app.firebaseapp.com',
    storageBucket: 'codingbahasa-app.firebasestorage.app',
    measurementId: 'G-XGZDWV4QSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1r3M1qQRYRSxAP5bEITdW75OtzZptV1Y',
    appId: '1:551649646330:android:ac01a5f7230d3faf435b43',
    messagingSenderId: '551649646330',
    projectId: 'codingbahasa-app',
    storageBucket: 'codingbahasa-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFcPeE6b5NuULHUHJudwKSs_3WjnJkUJA',
    appId: '1:551649646330:ios:1942388fdb3d65bb435b43',
    messagingSenderId: '551649646330',
    projectId: 'codingbahasa-app',
    storageBucket: 'codingbahasa-app.firebasestorage.app',
    iosBundleId: 'com.example.codingbahasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFcPeE6b5NuULHUHJudwKSs_3WjnJkUJA',
    appId: '1:551649646330:ios:1942388fdb3d65bb435b43',
    messagingSenderId: '551649646330',
    projectId: 'codingbahasa-app',
    storageBucket: 'codingbahasa-app.firebasestorage.app',
    iosBundleId: 'com.example.codingbahasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2twFMSRnLwzgkpVun6XZ5YbZCs-UqPao',
    appId: '1:551649646330:web:e14bc0ec36256011435b43',
    messagingSenderId: '551649646330',
    projectId: 'codingbahasa-app',
    authDomain: 'codingbahasa-app.firebaseapp.com',
    storageBucket: 'codingbahasa-app.firebasestorage.app',
    measurementId: 'G-QDH08SYEXT',
  );

}